meeting:
  transmit:
    app-bundle: com.zzedu.DepartMentalApp
    base-dir-path: ${ruoyi.profile}
    base-dir-name: bus-meeting
    sub-dir-db: DB
    sub-dir-draft: Draft
    # sub-dir-study: Study
    # sub-dir-material: Material
    source:
      all: ${meeting.transmit.base-dir-path}/${meeting.transmit.base-dir-name}
      path-db: ${meeting.transmit.source.all}/${meeting.transmit.sub-dir-db}
      path-draft: ${meeting.transmit.source.all}/${meeting.transmit.sub-dir-draft}
      # path-study: ${meeting.transmit.source.all}/${meeting.transmit.sub-dir-study}
      # path-material: ${meeting.transmit.source.all}/${meeting.transmit.sub-dir-material}
    target:
      all: ./data/storage/el2/base
      path-db: ${meeting.transmit.target.all}/${meeting.transmit.base-dir-name}
      # path-study: ${meeting.transmit.target.all}/${meeting.transmit.base-dir-name}/${meeting.transmit.sub-dir-study}
      # path-material: ${meeting.transmit.target.all}/${meeting.transmit.base-dir-name}/${meeting.transmit.sub-dir-material}